import { Listing } from '../types';

export const mockListings: Listing[] = [
  {
    id: '1',
    landlordId: 'landlord1',
    title: 'Modern 2BR Apartment Near Campus',
    description: 'Beautiful modern apartment with updated kitchen, spacious living room, and in-unit laundry. Perfect for students or young professionals.',
    address: '123 College Ave',
    city: 'Boston',
    state: 'MA',
    zipCode: '02115',
    college: 'Boston University',
    rent: 2800,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: ['Laundry', 'Parking', 'WiFi', 'Air Conditioning'],
    available: true,
    availableDate: new Date('2024-02-01'),
    coordinates: {
      latitude: 42.3505,
      longitude: -71.1054,
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    featured: true,
  },
  {
    id: '2',
    landlordId: 'landlord2',
    title: 'Cozy Studio in Harvard Square',
    description: 'Charming studio apartment in the heart of Harvard Square. Walking distance to Harvard University and public transportation.',
    address: '456 Harvard St',
    city: 'Cambridge',
    state: 'MA',
    zipCode: '02138',
    college: 'Harvard University',
    rent: 2200,
    bedrooms: 0,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: ['WiFi', 'Heat Included', 'Hardwood Floors'],
    available: true,
    availableDate: new Date('2024-01-25'),
    coordinates: {
      latitude: 42.3736,
      longitude: -71.1097,
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    featured: false,
  },
  {
    id: '3',
    landlordId: 'landlord3',
    title: 'Spacious 3BR House with Yard',
    description: 'Large house perfect for group living. Features include a full kitchen, living room, dining room, and private yard.',
    address: '789 Oak Street',
    city: 'Berkeley',
    state: 'CA',
    zipCode: '94704',
    college: 'UC Berkeley',
    rent: 4500,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: ['Parking', 'Yard', 'Dishwasher', 'Washer/Dryer', 'Pet Friendly'],
    available: true,
    availableDate: new Date('2024-03-01'),
    coordinates: {
      latitude: 37.8715,
      longitude: -122.2730,
    },
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    featured: true,
  },
  {
    id: '4',
    landlordId: 'landlord4',
    title: 'Modern 1BR with City Views',
    description: 'Stunning one-bedroom apartment with floor-to-ceiling windows and amazing city views. Premium building with amenities.',
    address: '321 Downtown Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90015',
    college: 'USC',
    rent: 3200,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: ['Gym', 'Pool', 'Concierge', 'Rooftop Deck', 'Air Conditioning'],
    available: false,
    availableDate: new Date('2024-02-15'),
    coordinates: {
      latitude: 34.0522,
      longitude: -118.2437,
    },
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    featured: false,
  },
  {
    id: '5',
    landlordId: 'landlord5',
    title: 'Shared Room in Student House',
    description: 'Affordable shared room in a friendly student house. Great for meeting new people and saving money.',
    address: '654 University Way',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98105',
    college: 'University of Washington',
    rent: 950,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: ['WiFi', 'Shared Kitchen', 'Study Room', 'Bike Storage'],
    available: true,
    availableDate: new Date('2024-01-20'),
    coordinates: {
      latitude: 47.6587,
      longitude: -122.3120,
    },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    featured: false,
  },
];

export const mockColleges = [
  'Boston University',
  'Harvard University',
  'MIT',
  'UC Berkeley',
  'UCLA',
  'USC',
  'University of Washington',
  'Stanford University',
  'Columbia University',
  'NYU',
  'University of Chicago',
  'Northwestern University',
];
